# Generated by Django 3.2.5 on 2021-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire',
            name='humidity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fire',
            name='output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fire',
            name='oxygen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fire',
            name='temperature',
            field=models.TextField(),
        ),
    ]
