# Generated by Django 3.2.5 on 2021-09-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210924_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fire',
            name='output',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fire',
            name='oxygen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fire',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
